name: JsPhp, A small JavaScript into PHP

on:
    pull_request:
    push:
        branches:
            - dev
            - master

jobs:
    test:
        name: Running Unit Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Unit Testing
              run: composer run-script test
