name: JsPhp, A small JavaScript into PHP

on:
    pull_request:
    push:
        branches:
            - dev
            - master

jobs:
    test:
        name: Running Unit Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key:
                      ${{ runner.os }}-node-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Unit Testing
              run: composer run-script test
